version: "3.8"
services:
  ecom-backend:
    build:
      context: "."
      dockerfile: "Dockerfile"
    container_name: ecom-backend
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - ecom-db

  ecom-db:
    image: mysql:8.0
    container_name: ecom-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3307:3306"
    env_file:
      - .env
    volumes:
      - ecom-mysql-data:/var/lib/mysql

volumes:
  ecom-mysql-data:
